language: php
dist: xenial
services:
  - mysql
  - docker
  - xvfb

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  # chrome: stable
  apt:
    packages:
      - tidy

matrix:
  fast_finish: true
  include:
    - php: 7.3

env:
  global:
    - DB=MYSQL
    - DISPLAY=":99"
    - XVFBARGS=":99 -ac -screen 0 1024x768x16"
    - SS_BASE_URL="http://localhost:8080/"
    - SS_ENVIRONMENT_TYPE="dev"
    - SS_BAMBUSA_SUPPRESS_MODAL=1

install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver chromium-browser
  - export PATH=~/.composer/vendor/bin:$PATH
  - pecl channel-update pecl.php.net
  - phpenv rehash
  - phpenv config-rm xdebug.ini || true
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Install composer dependencies
  - composer require --no-update -- silverstripe/recipe-testing:^1
  - composer require --no-update -- silverstripe/serve:^2;
  - composer update --prefer-source

  - mkdir artifacts; cp composer.lock artifacts/


script:
  - vendor/bin/phpunit --testsuite bambusa
  - composer run-script lint
  - phpdbg -qrr vendor/bin/phpunit --testsuite bambusa --coverage-clover=coverage.xml
  # - sh -e /etc/init.d/xvfb start
  - vendor/bin/serve --bootstrap-file vendor/silverstripe/cms/tests/behat/serve-bootstrap.php &> artifacts/serve.log &
  - sleep 3; chromedriver > artifacts/chromedriver.log 2>&1 &
  - vendor/bin/behat admin

deploy:
  # deploy the new image to DockerHub
  - provider: script
    script: bash docker/deploy.sh "$DOCKERHUB_USER" "$DOCKERHUB_PASSWORD" "$DOCKERHUB_IMAGE"
    on:
      branch: master
  - # report the outdated versions
    provider: script
    script: bash bin/composer-check-outdated.sh "$SLACK_WEBHOOK_URL"
    on:
      branch: master

after_failure:
  - php ./vendor/silverstripe/framework/tests/behat/travis-upload-artifacts.php --if-env ARTIFACTS_BUCKET,ARTIFACTS_KEY,ARTIFACTS_SECRET --target-path $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_BUCKET/ --artifacts-path ./artifacts/

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml
